In [1]:
pip install tf-keras

In [2]:
pip install tensorflow

In [3]:
pip install transformers

In [4]:
import tensorflow as tf

In [5]:
from transformers import BertTokenizer

In [6]:
from transformers import TFBertModel

In [7]:
tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

In [8]:
tokenizer

BertTokenizer(name_or_path='bert-base-uncased', vocab_size=30522, model_max_length=512, is_fast=False, padding_side='right', truncation_side='right', special_tokens={'unk_token': '[UNK]', 'sep_token': '[SEP]', 'pad_token': '[PAD]', 'cls_token': '[CLS]', 'mask_token': '[MASK]'}, clean_up_tokenization_spaces=True, added_tokens_decoder={
	0: AddedToken("[PAD]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	100: AddedToken("[UNK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	101: AddedToken("[CLS]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	102: AddedToken("[SEP]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	103: AddedToken("[MASK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
}
)

In [9]:
print(tokenizer)

BertTokenizer(name_or_path='bert-base-uncased', vocab_size=30522, model_max_length=512, is_fast=False, padding_side='right', truncation_side='right', special_tokens={'unk_token': '[UNK]', 'sep_token': '[SEP]', 'pad_token': '[PAD]', 'cls_token': '[CLS]', 'mask_token': '[MASK]'}, clean_up_tokenization_spaces=True, added_tokens_decoder={
	0: AddedToken("[PAD]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	100: AddedToken("[UNK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	101: AddedToken("[CLS]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	102: AddedToken("[SEP]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	103: AddedToken("[MASK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
}
)


In [10]:
sentence = "Welcome to BERT MODEL"
print(sentence)

Welcome to BERT MODEL


In [11]:
inputs  = tokenizer(sentence, return_tensors = "tf")
print(inputs)

{'input_ids': <tf.Tensor: shape=(1, 6), dtype=int32, numpy=array([[  101,  6160,  2000, 14324,  2944,   102]], dtype=int32)>, 'token_type_ids': <tf.Tensor: shape=(1, 6), dtype=int32, numpy=array([[0, 0, 0, 0, 0, 0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(1, 6), dtype=int32, numpy=array([[1, 1, 1, 1, 1, 1]], dtype=int32)>}


In [13]:
inputs.keys()

dict_keys(['input_ids', 'token_type_ids', 'attention_mask'])

In [14]:
inputs["input_ids"]

<tf.Tensor: shape=(1, 6), dtype=int32, numpy=array([[  101,  6160,  2000, 14324,  2944,   102]], dtype=int32)>

In [15]:
inputs["token_type_ids"]

<tf.Tensor: shape=(1, 6), dtype=int32, numpy=array([[0, 0, 0, 0, 0, 0]], dtype=int32)>

In [18]:
inputs["attention_mask"]

<tf.Tensor: shape=(1, 6), dtype=int32, numpy=array([[1, 1, 1, 1, 1, 1]], dtype=int32)>

In [20]:
input_ids = inputs["input_ids"]
attention_mask = inputs["attention_mask"]
token_type_ids = inputs["token_type_ids"]



In [21]:
print(input_ids)
print(attention_mask)
print(token_type_ids)

tf.Tensor([[  101  6160  2000 14324  2944   102]], shape=(1, 6), dtype=int32)
tf.Tensor([[1 1 1 1 1 1]], shape=(1, 6), dtype=int32)
tf.Tensor([[0 0 0 0 0 0]], shape=(1, 6), dtype=int32)


In [22]:
model = TFBertModel.from_pretrained("bert-base-uncased")

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`


model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFBertModel: ['cls.predictions.transform.dense.bias', 'cls.seq_relationship.bias', 'cls.predictions.bias', 'cls.predictions.transform.dense.weight', 'cls.seq_relationship.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.LayerNorm.bias']
- This IS expected if you are initializing TFBertModel from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFBertModel were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions w

In [23]:
outputs = model(input_ids, attention_mask = attention_mask, token_type_ids = token_type_ids)

In [24]:
outputs

TFBaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=<tf.Tensor: shape=(1, 6, 768), dtype=float32, numpy=
array([[[-0.03750956, -0.00240771,  0.09371928, ..., -0.13772789,
         -0.03129469,  0.14204504],
        [ 0.12140745, -0.53609264,  0.6310066 , ...,  0.55814695,
         -0.33416307,  0.12910849],
        [-1.1703508 , -0.31996158,  0.5275389 , ..., -0.38653016,
          0.05818313, -0.10520799],
        [ 0.25423813, -0.34890175,  0.6877104 , ..., -0.06853285,
          0.37479556, -0.3518722 ],
        [ 0.36494112,  0.43427455, -0.10789093, ..., -0.08007599,
          0.04822077, -0.5234004 ],
        [ 0.5539147 ,  0.24761598, -0.33582994, ..., -0.00767393,
         -0.7354609 , -0.44512182]]], dtype=float32)>, pooler_output=<tf.Tensor: shape=(1, 768), dtype=float32, numpy=
array([[-7.49955833e-01, -2.57069916e-01,  8.63632932e-02,
         5.89103639e-01, -1.82476416e-01, -7.54989833e-02,
         8.56075346e-01,  2.08281636e-01,  4.21756553e-03,
        -9

In [25]:
outputs.last_hidden_state

<tf.Tensor: shape=(1, 6, 768), dtype=float32, numpy=
array([[[-0.03750956, -0.00240771,  0.09371928, ..., -0.13772789,
         -0.03129469,  0.14204504],
        [ 0.12140745, -0.53609264,  0.6310066 , ...,  0.55814695,
         -0.33416307,  0.12910849],
        [-1.1703508 , -0.31996158,  0.5275389 , ..., -0.38653016,
          0.05818313, -0.10520799],
        [ 0.25423813, -0.34890175,  0.6877104 , ..., -0.06853285,
          0.37479556, -0.3518722 ],
        [ 0.36494112,  0.43427455, -0.10789093, ..., -0.08007599,
          0.04822077, -0.5234004 ],
        [ 0.5539147 ,  0.24761598, -0.33582994, ..., -0.00767393,
         -0.7354609 , -0.44512182]]], dtype=float32)>

In [26]:
last_hidden_state = outputs.last_hidden_state

In [27]:
last_hidden_state

<tf.Tensor: shape=(1, 6, 768), dtype=float32, numpy=
array([[[-0.03750956, -0.00240771,  0.09371928, ..., -0.13772789,
         -0.03129469,  0.14204504],
        [ 0.12140745, -0.53609264,  0.6310066 , ...,  0.55814695,
         -0.33416307,  0.12910849],
        [-1.1703508 , -0.31996158,  0.5275389 , ..., -0.38653016,
          0.05818313, -0.10520799],
        [ 0.25423813, -0.34890175,  0.6877104 , ..., -0.06853285,
          0.37479556, -0.3518722 ],
        [ 0.36494112,  0.43427455, -0.10789093, ..., -0.08007599,
          0.04822077, -0.5234004 ],
        [ 0.5539147 ,  0.24761598, -0.33582994, ..., -0.00767393,
         -0.7354609 , -0.44512182]]], dtype=float32)>

In [28]:
pooler_output = outputs.pooler_output

In [29]:
pooler_output

<tf.Tensor: shape=(1, 768), dtype=float32, numpy=
array([[-7.49955833e-01, -2.57069916e-01,  8.63632932e-02,
         5.89103639e-01, -1.82476416e-01, -7.54989833e-02,
         8.56075346e-01,  2.08281636e-01,  4.21756553e-03,
        -9.99637127e-01,  8.75877738e-02,  2.69920558e-01,
         9.50023830e-01, -7.29232207e-02,  8.62704396e-01,
        -3.87005657e-01,  1.14829071e-01, -4.33305681e-01,
         3.28514278e-01, -6.28143251e-01,  5.34155309e-01,
         9.51249301e-01,  5.53131104e-01,  2.05979988e-01,
         3.37003142e-01,  4.68114316e-01, -5.27339339e-01,
         8.54414582e-01,  9.09901261e-01,  5.81574082e-01,
        -5.63819528e-01,  1.54839978e-01, -9.51138318e-01,
        -1.55995846e-01,  7.72643648e-03, -9.60206628e-01,
         9.98708084e-02, -6.80168211e-01,  7.01318532e-02,
         6.34155888e-03, -7.61790872e-01,  2.40087643e-01,
         9.95175779e-01, -1.15126953e-01, -1.92190602e-01,
        -2.22133607e-01, -9.99597192e-01,  1.68801531e-01,
      

In [30]:
last_hidden_state.shape

TensorShape([1, 6, 768])

In [31]:
pooler_output.shape

TensorShape([1, 768])